### ISSUE TITLE
Jets fails to create a custom domain

### ISSUE THREAD

**Issue by wr0ngway** [tongueroo/jets#385]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    docker ruby:2.5.7 (linux 4.9.184-linuxkit)    |
| Jets             |   2.3.0      |
| Ruby             |   2.5.7p206      |

---

## Expected Behaviour

Jets should create a custom domain without failing

## Current Behavior

I'm using jets to deploy a new project which only has a hello world controller in it.  It deploys successfully until I try to add a custom domain, at which time the jets deploy process takes about 30-60 minutes before finally failing while trying to update the ApiGateway with `Too Many Requests (Service: AmazonApiGateway; Status Code: 429; Error Code: TooManyRequestsException; Request ID: xxxx)`

Immediately before or after, I'm able to create a custom domain (only takes a few seconds) with the same settings in the aws console, so its not hitting an account limit specifically for this unless CF is doing something funky...?

## Step-by-step reproduction instructions
```
jets new
add something simple
jets deploy
add custom domain config
jets deploy
```

## Code Sample

application.rb contains:
```
  config.domain.hosted_zone_name = "dev.mydomain.com"
  config.domain.name = "#{config.project_name}.#{domain}"
  config.domain.cert_arn = "arn:aws:acm:us-east-1:xxx:certificate/xxx"
  config.domain.route53 = false
```
/tmp/jets/myproj/templates/myproj-dev-api-gateway.yml contains:
```
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: myproj.dev.mydomain.com
      EndpointConfiguration:
        Types:
        - REGIONAL
      RegionalCertificateArn: arn:aws:acm:us-east-1:xxx:certificate/xxx
```
